ppsv/backend/urls.py
from django.urls import path, include

from . import views

app_name = "backend"

urlpatterns = [
    path('assignment/', views.assignment_page, name='assignment_page'),
    path('home/', views.home_page, name='home_page'),
    path('export-applications-and-assignments/', views.export_applications_and_assignments_page,
         name='export_applications_and_assignments_page'),
    path('admin_functionality/', views.admin, name='admin_page'),
    path('term_finalized/',views.term_finalized, name='term_finalized'),
    # path('__debug__/', include('debug_toolbar.urls')),

]

ppsv/frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('your_selection/', views.your_selection, name='your_selection'),
    path('overview/', views.overview, name='overview'),
    path('groups/', views.groups, name='groups'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

ppsv/ppsv/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('backend.urls')),
    path('', include('teachers.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ppsv/teachers/urls.py
from django.urls import path
from . import views

app_name = "teachers"

urlpatterns = [
    path('teachers/', views.overview_page, name='overview_page')
]

ppsv/backend/models.py
from django.core.exceptions import ValidationError
from django.db import models

from course.models import Group
from course.models import Group
from course.models import Topic
from course.models import Topic
from course.models import TopicSelection
from course.models import TopicSelection, Term


class Assignment(models.Model):
    """ Assignment

    This model represents a slot to which applications can be assigned. An Assignment contains a topic, a slotID, all
    assigned applications and can be finalized so that no applications can be assigned or removed from this assignment.

    :attr Assignment.topic: The foreign key of a topic
    :type Assignment.topic: ForeignKey
    :attr Assignment.slot_id: The foreign key of a topic selection
    :type Assignment.slot_id: PositiveIntegerField
    :attr Assignment.accepted_applications: The accepted applications
    :type Assignment.accepted_applications: ManyToManyField through class AcceptedApplications
    :attr Assignment.finalized_slot: 0 if the assignment is not finalized, 1 if the assignment is finalized on the
    assignment page, 2 if the assignment was finalized by an admin, but it previously wasn't finalized and 3 if the
    assignment was finalized by an admin and it previously was finalized on the assignment page
    :type Assignment.finalized_slot: PositiveIntegerField
    """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="Topic")
    slot_id = models.PositiveIntegerField("SlotID")
    accepted_applications = models.ManyToManyField(TopicSelection, verbose_name="Accepted Applications",
                                                   through="AcceptedApplications")
    finalized_slot = models.PositiveIntegerField(default=0)

    @property
    def open_places_in_topic_count(self):
        """places in topic
        :return: returns the count of all open places (per student) for the topic of this assignment
        :rtype: int
        """
        open_assignment_count = self.topic.max_slot_size * self.topic.max_slots
        for assignment in Assignment.objects.filter(topic=self.topic):
            open_assignment_count -= self.topic.max_slot_size - assignment.open_places_in_slot_count
        return open_assignment_count

    @property
    def locked(self):
        return self.finalized_slot != 0

    @property
    def open_places_in_slot_count(self):
        """places in slot
        :return: returns the count of all open assignments (per student) for this slot
        :rtype: int
        """
        open_assignment_count = self.topic.max_slot_size
        for applications in self.accepted_applications.all():
            open_assignment_count -= applications.group.size
        return open_assignment_count

    @staticmethod
    def assigned_student_to_topic_count(topic):
        """assigned to topic
        :return: returns the count of all assigned students for the topic of this assignment
        :rtype: int
        """
        all_assignment_count = 0
        for assignment in Assignment.objects.filter(topic=topic, topic__course__term=Term.get_active_term()):
            all_assignment_count += assignment.assigned_student_to_slot_count
        return all_assignment_count

    @staticmethod
    def has_open_places(topic):
        """returns how many open places (students) are remaining for this topic"""
        all_assignment_count = 0
        max_assignments = topic.max_slot_size * topic.max_slots
        for assignment in Assignment.objects.filter(topic=topic, topic__course__term=Term.get_active_term()):
            all_assignment_count += assignment.assigned_student_to_slot_count
        return max_assignments - all_assignment_count

    @property
    def assigned_student_to_slot_count(self):
        """assigned to slot
        :return: returns the count of all assigned students for this slot
        :rtype: int
        """
        assignment_count = 0
        for application in self.accepted_applications.all():
            assignment_count += application.group.size
        return assignment_count

    @property
    def max_assigned_student_to_slot(self):
        """
        :return: returns the maximum amount of students that can be assigned to slot of the corresponding topic
        :rtype: int
        """
        return self.topic.max_slot_size

    @property
    def any_application_locked(self):
        """
        :return: Returns true, if any corresponding accepted applications are locked
        :rtype: Boolean
        """

        for app in AcceptedApplications.objects.filter(assignment=self):
            if app.locked:
                return True
        return False

    def __str__(self):
        if self.topic.is_group_topic:
            return "Slot " + str(self.slot_id) + " of topic \"" + self.topic.title + "\" [" + str(
                self.assigned_student_to_slot_count) + "/" + str(self.topic.max_slot_size) + "]"
        else:
            return "Slot " + str(self.slot_id) + " of topic \"" + self.topic.title + "\""

    def clean(self):
        # SlotID Unique
        query = Assignment.objects.filter(topic=self.topic, slot_id=self.slot_id)
        if query.exists() and not (query.count() == 1 and query.contains(self)):
            raise ValidationError("Slot IDs need to be unique")

        # # Groups cant be in multiple slots of the same topic
        # groups = []
        # for assignment in Assignment.objects.filter(topic=self.topic):
        #     groups.append(assignment.accepted_applications.groups.all())
        # for groups in groups:
        #     for group in groups.all():
        #         if self.groups.contains(group):
        #             raise ValidationError("This group is already in another slot")

        # check if max_slot_size of topic is not exceeded (if min_size is not satisfied the assignment can be stored but not published)
        student_count = self.assigned_student_to_slot_count

        if student_count > self.topic.max_slot_size:
            raise ValidationError("This assignment exceeds the maximum slot size of the assigned topic")


class AcceptedApplications(models.Model):
    """ AcceptedApplications

    This model represents that an application is accepted via the specified assignment. An AcceptedApplications contains
    an assignment, a TopicSelection and can be finalized so that it can't be changed anymore.

    :attr AcceptedApplications.assignment: The foreign key of an assignment
    :type AcceptedApplications.assignment: ForeignKey
    :attr AcceptedApplications.topic_selection: The foreign key of a topic selection
    :type AcceptedApplications.topic_selection: ForeignKey
    :attr AcceptedApplications.finalized_assignment: True if the assignment is finalized
    :type AcceptedApplications.finalized_assignment: BooleanField
    """
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    topic_selection = models.ForeignKey(TopicSelection, on_delete=models.CASCADE)
    finalized_assignment = models.BooleanField(default=False)

    @property
    def locked(self):
        return self.finalized_assignment

    @classmethod
    def get_collection_dict(cls):
        """
        :return: a dict with keys (group, collection_number) and values accepted application
        :rtype: QuerySet
         """
        collection_dict = {}
        for application in cls.objects.filter(assignment__topic__course__term=Term.get_active_term()):
            application = application.topic_selection
            collection_dict[application.dict_key] = application

        return collection_dict


class TermFinalization(models.Model):
    """ Saves if a term is finalized or not"""
    term = models.ForeignKey(Term, on_delete=models.CASCADE)
    mails_send = models.BooleanField(default=False)
    finalized = models.BooleanField(default=False)

    @staticmethod
    def is_finalized(term):
        query = TermFinalization.objects.filter(term=term)
        if not query.exists():
            return False
        return query.get().finalized

ppsv/backend/views.py
from django.shortcuts import render

from .pages.admin_page import admin_page
from .pages.assignment_page import assignment_page
from .pages.home_page import home_page
from .pages.export_applications_and_assignments_page import export_applications_and_assignments_page


# Create your views here.


def assignment_view(request):
    assignment_page(request)


def home_view(request):
    home_page(request)


def export_applications_and_assignments_view(request):
    export_applications_and_assignments_page(request)


def admin(request):
    # wtf warum?!
    return admin_page(request)


def term_finalized(request):
    return render(request, 'backend/term_finalized.html')

ppsv/backend/templates/backend/admin.html
{% extends 'backend/base.html' %}
{% load static %}
{% load i18n %}

{% block tab_name %}
    Admin Control
{% endblock tab_name %}

{% block title %}
    Admin Control
{% endblock title %}

{% block additional_buttons %}
    {% if user.is_authenticated %}
        {% if user.is_staff %}
            <a href="{% url 'backend:home_page' %}"
               class="adminbtn btn btn-danger navbar-inline-list">
                Home Page </a>
            <a href="{% url 'backend:assignment_page' %}"
               class="adminbtn btn btn-danger navbar-inline-list">
                Assignment Page </a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Custom Admin Actions</h1>
    <div id="admin-actions">
        <div class="section">
            <span>Finalisation Actions</span>
            <div id="automaticAssignmentDiv" class="text-button">
                <button id="automaticAssignment" class="{% if running %} running {% endif %}"
                        onclick="automaticAssignment(true)"><i
                        class="fa fa-check" aria-hidden="true"></i>
                </button>
                <p>Start an automatic Assignment with Override</p>
                <div id="automaticAssignmentProgress">
                    <div class="text"></div>
                </div>
            </div>
            <div id="finalizeAllAssignmentsDiv" class="text-button">
                <button id="finalizeAllAssignments" onclick="finalizeAllAssignments(true)"><i
                        class="fa fa-check" aria-hidden="true"></i>
                </button>
                <p>Lock and Finalize all Assignments. Only possible if all Slots are filled correctly</p>
            </div>
            <div id="unfinalizeAllAssignmentsDiv" class="text-button">
                <button id="unfinalizeAllAssignments" onclick="finalizeAllAssignments(false)"><i
                        class="fa fa-check" aria-hidden="true"></i>
                </button>
                <p>Unlock all Assignments</p>
            </div>
            <div id="sendEmailsDiv" class="text-button">
                <button id="sendEmails" onclick="sendEmails()"><i
                        class="fa fa-check" aria-hidden="true"></i>
                </button>
                <p>Send Emails</p>
            </div>
        </div>
        <div class="section">
            <span>Change active/shown Term</span>
            <div id="selectTermDiv" class="text-button">
                <button id="selectTerm"
                        onclick="changeActiveTerm()"><i
                        class="fa fa-save" aria-hidden="true"></i>
                </button>
                <p>Change the active/shown Term for Students and Administrator</p>
                <select id="selectTermSelect" name="term">
                    {% for term in terms %}
                        <option value="{{ term }}" {% if term == activeTerm %} selected
                                style="background: var(--green)" {% endif %} >{{ term }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="section">
            <span>Removals</span>
            <div id="removeBrokenSlotsDiv" class="text-button">
                <button id="removeBrokenSlots" onclick="removeBrokenSlots()"><i
                        class="fa fa-trash" aria-hidden="true"></i>
                </button>
                <p>Remove all applications from all Slots with Errors</p>
            </div>
        </div>
    </div>

    <!-- script block for finalisation actions -->
    <script>

        /**
         * Sends an ajax request to the backend to send emails to all students that have selected a topic in the current term.
         */
        function sendEmails() {
            if (confirm("Do you really want to send all Emails to all Students now?")) {
                $.ajax({
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: "sendEmails",
                    },
                    method: "POST",
                    success: () => {
                        alert("Emails send!");
                    }
                });
            }

        }

        let assignmentRunning = {% if running %} true {% else %} false {% endif %}

        /**
         * Sends an ajax request to the backend to start the automatic assignment.
         * @param override if true override all non-locked slots and applications if it finds a better result
         */
        function automaticAssignment(override) {
            if (assignmentRunning) {
                window.alert("This process is already running");
                return;
            }
            if (override) {
                if (!confirm("This will override all non locked slots and applications if it finds a better result!\nDo you want to continue?")) {
                    return
                }
            }
            startAutoUpdate();

            assignmentRunning = true;
            $('#automaticAssignmentProgress').show();
            $('#automaticAssignment').addClass('running');
            $('#automaticAssignment i').addClass('fa-spin');
            $('#automaticAssignmentNoOverride').addClass('running');
            $('#automaticAssignmentNoOverride i').addClass('fa-spin');


            $.ajax({
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: "startAutomaticAssignment",
                    override: override
                },
                method: "POST",
            });
        }


        let autoQuery

        /**
         * Starts an interval to query the backend for the progress of the automatic assignment.
         */
        function startAutoUpdate() {
            if (autoQuery != null)
                return
            autoQuery = setInterval(function () {
                $.ajax({
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: "getAssignmentProgress",
                    },
                    method: "POST",
                    dataType: "json",
                    success: (data) => {

                        $("#automaticAssignmentProgress").progressbar("value", data['progress']);
                        $("#automaticAssignmentProgress .text").text(data['progress'] + "%     " + data['eta']);
                        if (!data['running']) {
                            $('#automaticAssignment').removeClass('running');
                            $('#automaticAssignment i').removeClass('fa-spin');
                            $('#automaticAssignmentNoOverride').removeClass('running');
                            $('#automaticAssignmentNoOverride i').removeClass('fa-spin');

                            $('#automaticAssignmentProgress').hide();
                            assignmentRunning = false

                            clearInterval(autoQuery);
                            autoQuery = null;
                        }
                    }
                });
            }, 250)
        }

        /**
         *
         * @param finalize if true lock if false unlock
         */
        function finalizeAllAssignments(finalize) {
            $.ajax({
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: "finalize",
                    finalize: finalize,
                },
                method: "POST",
                dataType: "json",
                success: (data) => {
                    if (finalize) {
                        if (data["success"])
                            alert("Finalized");
                        else
                            alert("Could not finalize. There are Slots with Errors");
                    } else {
                        alert("Finalization deleted");
                    }
                }
            });
        }

        $(document).ready(
            function () {
                $('#automaticAssignmentProgress').progressbar({
                    value: 0
                });
                if (assignmentRunning) {
                    $('#automaticAssignmentProgress').show();
                    $('#automaticAssignment').addClass('running');
                    $('#automaticAssignment i').addClass('fa-spin');
                    $('#automaticAssignmentNoOverride').addClass('running');
                    $('#automaticAssignmentNoOverride i').addClass('fa-spin');
                    startAutoUpdate();
                } else {
                    $('#automaticAssignmentProgress').hide();
                }
            }
        );
    </script>

    <!-- script block for change term -->
    <script>
        /**
         * Sends an ajax request to the backend to change the currently active term.
         */
        function changeActiveTerm() {
            $.ajax({
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: "changeTerm",
                    newTerm: $('#selectTermSelect').val(),
                },
                method: "POST",
                success: () => {
                    alert("Term changed!");
                    location.reload();
                }
            });
        }
    </script>

    <!-- script block for removals -->
    <script>
        /**
         * Sends an ajax request to the backend to remove all applications from all Slots with Errors.
         */
        function removeBrokenSlots() {
            if (confirm("Delete all assignments from all Slots with Errors? \nIgnores finalized status \nASSIGNMENTS ARE NOT RECOVERABLE!")) {
                $.ajax({
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: "removeBrokenSlots",
                    },
                    method: "POST",
                    success: () => {
                        alert("Slots with Errors cleared");
                    }
                });
            }
        }
    </script>

    <!-- initialize default error message for post request -->
    <script>
        $.ajaxSetup({
            error: function (error) {
                alert("Server error on request!\n Check for critical Slots with Errors or contact an administrator! (╯°□°)╯︵ ┻━┻ Oh wait you are the administrator. Well good luck fixing the problem and sorry for the inconvenience \n" + error.statusText + "\n " + error.responseText);
            }
        })
    </script>
{% endblock %}

ppsv/backend/templates/backend/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>

    <!-- This page contains all elements which all pages will use -->

    <!-- Sets the character set of all html pages which extend base.html -->
    <meta charset="UTF-8">

    <!-- Defines a block where other html pages can use their own title -->
    <title>{% block tab_name %} {% endblock %}</title>


    <!-- Imports all important stylesheets and hyper references for all html pages which extend base.html -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/ppsv.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Arvo&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'backend/css/jQuery.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'backend/css/style.css' %}">


    <!-- JQuery & JQuery UI Integration -->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <!-- Our JS -->
    <script src="{% static 'backend/js/cookie.js' %}"></script>


</head>


<body>
<!-- Both "header" and "navbar" will be included in all html pages which extend "base.html" -->


<!-- "header" contains on the left side the page name and on the right side a logo and the name of the user which is
logged in right now. If a user is logged in, a logout button is displayed. If not, a login button is displayed. -->
{% if not is_popup %}
    <!-- Header -->
    <div id="header" class="header-background">
        <div class="white-strip"></div>
        <div id="header-content">
            <h3><a class="default_look"
                   href="{% url 'backend:home_page' %}"> {% translate "Internship & Seminar Allocation" %} -
                {% block title %} {% endblock %} </a></h3>
            <div id="controls">
                {% block additional_buttons %}
                {% endblock %}
                {% if user.is_authenticated %}
                    <a href="{% url 'teachers:overview_page' %}" class="adminbtn btn btn-danger navbar-inline-list">
                        Teachers page</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'admin:index' %}" class="adminbtn btn btn-danger navbar-inline-list">
                            Django Admin</a>
                        <a href="{% url 'backend:admin_page' %}" class="adminbtn btn btn-danger navbar-inline-list">
                            Admin Controls</a>
                    {% endif %}
                {% endif %}
                <div class="login-box">
                    <!-- user_menu -->
                    <div class="user-menu">
                        {% block login %}
                            {% if user.is_authenticated %}
                                {{ user.username }} (<a href="{% url 'frontend:logout' %}">Logout</a>)
                            {% else %}
                                {% translate "You are not logged in." %}
                                (<a href="{% url 'frontend:login' %}">Login</a>)
                            {% endif %}
                        {% endblock %}
                    </div>
                    <a class="login-link" href="{% url 'frontend:login' %}"><i
                            class="fa fa-user-circle-o fa-3x"></i></a>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div id="base">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

ppsv/backend/templates/backend/term_finalized.html
{% extends 'frontend/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <h1>{% translate "The currently active Term is finalized." %}</h1>
{% endblock %}