ppsv/backend/urls.py
from django.urls import path, include

from . import views

app_name = "backend"

urlpatterns = [
    path('assignment/', views.assignment_page, name='assignment_page'),
    path('home/', views.home_page, name='home_page'),
    path('export-applications-and-assignments/', views.export_applications_and_assignments_page,
         name='export_applications_and_assignments_page'),
    path('admin_functionality/', views.admin, name='admin_page'),
    path('term_finalized/',views.term_finalized, name='term_finalized'),
    # path('__debug__/', include('debug_toolbar.urls')),

]

ppsv/frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('your_selection/', views.your_selection, name='your_selection'),
    path('overview/', views.overview, name='overview'),
    path('groups/', views.groups, name='groups'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

ppsv/ppsv/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('backend.urls')),
    path('', include('teachers.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ppsv/teachers/urls.py
from django.urls import path
from . import views

app_name = "teachers"

urlpatterns = [
    path('teachers/', views.overview_page, name='overview_page')
]

ppsv/frontend/forms/forms.py
"""Purpose of this file
This file contains forms associated with the frontend.
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.forms import ModelForm
from course.models import Student
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.utils.functional import lazy

mark_safe_lazy = lazy(mark_safe, str)


class NewUserForm(UserCreationForm):
	"""New User Form
	represents the form to create new users

	:attr email: Input Field for the email
	:type email: EmailField
	"""

	email = forms.EmailField(required=True, widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'E-Mail'}), label='')

	class Meta:
		"""Meta options
		This class handles all possible meta options that you can give to this form.
		:attr Meta.model: The model to which this form corresponds
		:type Meta.model: Model
		:attr Meta.fields: Including fields into the form
		:type Meta.fields: str or list[str]
		"""
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		"""Save function for saving the newly created user

		:param commit: if the user should be saved
		:return: user
		"""
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

	# formatting of the form
	username = UsernameField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': _('username'), 'id': 'username'}), label='', help_text=
				mark_safe_lazy(_(
					"<div style=\"padding-left: 10px\"><small>Letters, numbers and @/./+/-/_ only."
					"</small></div>")))
	password1 = forms.CharField(widget=forms.PasswordInput(
		attrs={'class': 'form-control', 'placeholder': _('password'), 'id': 'password1'}
	), label='')
	password2 = forms.CharField(widget=forms.PasswordInput(
		attrs={'class': 'form-control',	'placeholder': _('confirm password'), 'id': 'password2'}
	), label='', help_text=mark_safe_lazy(_(
									"<div style=\"padding-left: 10px\"><small>"
									"The password must not contain any personal information.<br>"
									"The password has to be at least 8 digits long.<br>"
									"The password must not be commonly used.<br>"
									"The password must not contain only numbers.</small></div>")))


class NewStudentForm(ModelForm):
	"""New Student form
	represents the form for creating a new student for the current user.

	:attr tucan_id: The TUCaN-ID of the student
	:type tucan_id: CharField
	:attr firstname: The first name of the student
	:type firstname: CharField
	:attr lastname: The last name of the student
	:type lastname: CharField
	"""
	tucan_id = forms.CharField(min_length=8, max_length=8, required=True, widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'TU-ID'}), label='')
	firstname = forms.CharField(max_length=200, required=True, widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': _('first name')}), label='')
	lastname = forms.CharField(max_length=200, required=True, widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': _('last name')}), label='')

	class Meta:
		"""Meta options
		This class handles all possible meta options that you can give to this form.
		:attr Meta.model: The model to which this form corresponds
		:type Meta.model: Model
		:attr Meta.fields: Including fields into the form
		:type Meta.fields: str or list[str]
		"""
		model = Student
		fields = ("tucan_id", "firstname", "lastname")


class UserLoginForm(AuthenticationForm):
	"""UserLoginForm
	represents the login form for users.

	:attr username: The input field for the username
	:type username: UsernameField
	:attr password: The input field for the username
	:type password: CharField
	"""

	# formatting of the form
	username = UsernameField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': _('username'), 'id': 'username'}), label='')
	password = forms.CharField(widget=forms.PasswordInput(
		attrs={
			'class': 'form-control',
			'placeholder': _('password'),
			'id': 'password',
		}
	), label='')

ppsv/frontend/views.py
"""Purpose of this file
This file describes the frontend views.
"""
from django.apps import apps
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _

from course import models
from course.models import TopicSelection, Group, Term
from frontend.decorators import user_passes_test
from .forms.forms import NewUserForm, NewStudentForm, UserLoginForm


def check_domain(func):
    def wrapper(request, *args, **kwargs):
        if apps.is_installed("django.contrib.admin"):
            from backend.models import TermFinalization
            if TermFinalization.is_finalized(Term.get_active_term()):
                return redirect("backend:term_finalized")
        return func(request, *args, **kwargs)

    return wrapper


@check_domain
def homepage(request):
    """View for homepage
    :param request: The given request
    :return: HttpRequest
    """
    template_name = 'frontend/homepage.html'

    if request.user.is_authenticated:
        if hasattr(request.user, "student"):
            # In order to pin messages on the "What to do next" board, one needs to add the message
            # as a key to "recommendations" and the link as the value
            args = {}
            recommendations = {}

            groups_of_student = models.Group.objects.filter(students=request.user.student, term=Term.get_active_term())
            selections_exist = False
            selections_need_motivation = False
            need_to_assign_topics_to_collection = False
            collection_has_mixed_course_types = False
            for group in groups_of_student:
                if models.TopicSelection.objects.filter(group=group,
                                                        topic__course__term=Term.get_active_term()).exists():
                    selections_exist = True
                    break

            for group in groups_of_student:
                if models.TopicSelection.objects.filter(group=group, motivation="",
                                                        topic__course__term=Term.get_active_term()).exists():
                    for selection in models.TopicSelection.objects.filter(group=group, motivation="",
                                                                          topic__course__term=Term.get_active_term()):
                        if selection.topic.course.motivation_text:
                            selections_need_motivation = True
                            break

            for group in groups_of_student:
                if models.TopicSelection.objects.filter(group=group, collection_number=0,
                                                        topic__course__term=Term.get_active_term()).exists():
                    need_to_assign_topics_to_collection = True
                    break

            # check for a collection that has mixed course types
            for group in groups_of_student:
                # collection 0 is allowed to have mixed types of courses
                for collection in range(1, group.collection_count + 1):
                    # check if there are topics in the selection
                    if models.TopicSelection.objects.filter(group=group, collection_number=collection,
                                                            topic__course__term=Term.get_active_term()).exists():
                        topics_in_current_collection = models.TopicSelection.objects.filter(
                            group=group, collection_number=collection, topic__course__term=Term.get_active_term())
                        # only look at collections with one or more entry
                        if topics_in_current_collection.count() > 1:
                            course_type_of_first_topic = topics_in_current_collection[0].topic.course.type
                            for topic_to_check in topics_in_current_collection:
                                # check if there are different course types in this collection
                                if not topic_to_check.topic.course.type == course_type_of_first_topic:
                                    collection_has_mixed_course_types = True
                                    break
                            else:
                                continue
                            break
                else:
                    continue
                break

            # Pins message to board if motivation texts are missing for selections
            if need_to_assign_topics_to_collection:
                msg = "You still need to assign at least one topic to a collection!"
                link = "frontend:your_selection"
                recommendations[msg] = link

            # Pins message to board if motivation texts are missing for selections
            if selections_need_motivation:
                msg = _("You still need to write one or more motivation texts!")
                link = "frontend:your_selection"
                recommendations[msg] = link

            # Pins message to board if the user has mixed course types in a collection
            if collection_has_mixed_course_types:
                msg = _("There is at least one collection that has mixed course types!")
                link = "frontend:your_selection"
                recommendations[msg] = link

            # Pins message to board if no selections were made
            if not selections_exist:
                msg = _("You have not selected any topics yet!")
                link = "frontend:overview"
                recommendations[msg] = link
            # Otherwise show where they can be managed
            else:
                msg = _("You can view and manage your selected topics and collections here:")
                link = "frontend:your_selection"
                recommendations[msg] = link

            # Pins message to board if no group was created
            if len(models.Group.objects.filter(students=request.user.student, term=Term.get_active_term())) <= 1:
                msg = _("You can create a group here:")
                link = "frontend:groups"
                recommendations[msg] = link

            args["recommendations"] = recommendations
            return render(request, template_name, args)
        else:
            return render(request, template_name)

    else:
        return login_request(request, template_name)


@check_domain
def overview(request):
    """View for overview page

    :param request: The given request
    :return: HttpRequest
    """
    template_name = 'frontend/overview.html'

    args = {}
    if request.method == "POST":
        # Display all faculties when coming back from somewhere else in overview
        if "faculty_view" in request.POST:

            all_faculties = models.Course.objects.filter(term=Term.get_active_term()).values(
                "faculty").distinct().order_by("faculty")

            faculties = {}
            for faculty in all_faculties:
                course = models.Course.objects.filter(faculty=faculty["faculty"], term=Term.get_active_term())
                faculties[faculty.get("faculty")] = course[0].get_faculty_display()

            args["faculties"] = faculties
        # when a faculty is chosen show its courses
        elif "choose_faculty" in request.POST:

            if "|" in str(request.POST.get("choose_faculty")):
                data = str(request.POST.get("choose_faculty")).split("|")
                chosen_faculty = data[0]
                args["sortBy"] = data[1]
                if "dsc" in data[2]:
                    args["dsc"] = True
                else:
                    args["dsc"] = False
            else:
                chosen_faculty = str(request.POST.get("choose_faculty"))

            courses_in_chosen_faculty = models.Course.objects.filter(faculty=chosen_faculty,
                                                                     term=Term.get_active_term())

            # sorts "courses_in_chosen_faculty"
            if "|" in str(request.POST.get("choose_faculty")):
                if "status" in data[1]:
                    if "dsc" in data[2]:
                        courses_in_chosen_faculty = \
                            sorted(courses_in_chosen_faculty, key=lambda x: x.get_status)[::-1]
                    else:
                        courses_in_chosen_faculty = sorted(courses_in_chosen_faculty, key=lambda x: x.get_status)
                else:
                    if "dsc" in data[2]:
                        courses_in_chosen_faculty = list(courses_in_chosen_faculty.order_by("-" + data[1]))
                    else:
                        courses_in_chosen_faculty = list(courses_in_chosen_faculty.order_by(data[1]))

            args["chosen_faculty"] = chosen_faculty
            if len(courses_in_chosen_faculty) != 0:
                available = False
                for course in courses_in_chosen_faculty:
                    if course.get_status in ["Imminent", "Open"]:
                        available = True
                        break
                if available:
                    args["courses"] = courses_in_chosen_faculty
                else:
                    args["courses"] = "No_Courses"

        # when a course is chosen display its topics
        elif "choose_course" in request.POST:

            data = str(request.POST.get("choose_course")).split("|")
            chosen_course = data[0]
            chosen_faculty = data[1]
            open_course_info = data[2]

            topics_in_chosen_course = models.Topic.objects.filter(course=chosen_course,
                                                                  course__term=Term.get_active_term())

            args["chosen_faculty"] = chosen_faculty

ppsv/frontend/templates/frontend/base.html
{% load static %}
{% load i18n %}
{% load auth_extras %}

<html>
<head>

    <!-- This page contains all elements which all pages will use -->

    <!-- Sets the character set of all html pages which extend base.html -->
    <meta charset="UTF-8">

    <!-- Defines a block where other html pages can use their own title -->
    <title>{% block title %} {% endblock %}</title>

    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Imports all important stylesheets and hyper references for all html pages which extend base.html -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dropdown.css' %}">
    <link rel="stylesheet" href="{% static 'css/ppsv.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Arvo&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">

</head>

<body>

<!-- Both "header" and "navbar" will be included in all html pages which extend "base.html" -->

<!-- "header" contains on the left side the page name and on the right side a logo and the name of the user which is
logged in right now. If a user is logged in, a logout button is displayed. If not, a login button is displayed. -->
<div name="header" class="container-fluid" style="background-color: #0a3d62;padding-left:50px;padding-right:50px;padding-bottom:10px;padding-top:20px;color:#ffffff;height:100px">
    <div style="background-color: white;height: 5px; width: 100%;margin-bottom:20px"> </div>
    <h3 style="font-weight: 500;font-family-sans-serif: 'Roboto'"> {% translate "Internship & Seminar Allocation" %} </h3>
    <div style="position:absolute;right:50px;top:37px;display: flex; flex-direction: row;">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href="{% url 'backend:home_page' %}" class="btn btn-danger navbar-inline-list" style="height:35px;margin-top:5px;margin-right:5px">
                Assignment Home Page</a>
            {% endif %}
            {% if request.user|has_group:"teacher" or user.is_staff %}
                <a href="{% url 'teachers:overview_page' %}" class="btn btn-danger navbar-inline-list" style="height:35px;margin-top:5px;margin-right:5px">
                Teachers Page</a>
            {% endif %}
            {% if user.is_superuser %}
            <a href="{% url 'admin:index' %}" class="btn btn-danger navbar-inline-list" style="height:35px;margin-top:5px">
                Django Admin
            </a>
            {% endif %}
        {% endif %}
        <!-- user_menu -->
        <div style="display:flex; flex-direction: row; justify-content: right; align-items: right;margin-left:10px;margin-top:10px">
            {% block login %}
                {% if user.is_authenticated %}
                    {{ user.username }} (<a href="{% url 'frontend:logout' %}">Logout</a>)
                {% else %}
                    {% translate "You are not logged in." %}
                    (<a href="{% url 'frontend:login' %}">Login</a>)
                {% endif %}
            {% endblock %}

        </div>
        <a style="color: white;" href="{% url 'frontend:login' %}"><i class="fa fa-user-circle-o fa-3x" aria-hidden="true" style="margin-left:10px;"></i></a>
        </div>
</div>

<!-- "navbar" contains all links to important html pages like the homepage,overview etc. -->
<div name="navbar" class="container-fluid" style="background-color: #0C8FCC;padding-left:50px;padding-right:50px;width:100%">
    <div class="row" style="width:100%;">
        {% block homepage_navbar_container %}
        <form class="navbar-form" action="{% url 'frontend:homepage' %}" style="float:left;padding-bottom: 0px;">
            <button type="submit" class="navbar-btn" style="padding-top:0.42em;padding-bottom:0.42em;"> <i class="fa fa-home fa-lg" aria-hidden="true" style="font-size:26px"> </i></button>
        </form>
        {% endblock homepage_navbar_container %}
        {% block selection_page_navbar_container %}
        <form class="navbar-form" action="{% url 'frontend:overview' %}" style="float:left;padding-bottom: 0px">
            <button type="submit" class="navbar-btn" style="padding-bottom: 0.3em;padding-top: 0.3em"> {% translate "Overview" %} </button>
        </form>
        {% endblock selection_page_navbar_container %}
        {% if user.is_authenticated %}
        {% block your_selection_page_navbar_container %}
        <form class="navbar-form" action="{% url 'frontend:your_selection' %}" style="float:left;padding-bottom: 0px">
            <button type="submit" style="padding-bottom: 0.3em;padding-top: 0.3em" class="navbar-btn"> {% translate "My Selection" %} </button>
        </form>
        {% endblock your_selection_page_navbar_container %}
        {% endif %}
        {% if user.is_authenticated %}
        {% block groups_page_navbar_container %}
        <form class="navbar-form" action="{% url 'frontend:groups' %}" style="float:left;padding-bottom: 0px">
            <button type="submit" style="padding-bottom: 0.3em;padding-top: 0.3em" class="navbar-btn"> {% translate "My Groups" %} </button>
        </form>
        {% endblock groups_page_navbar_container %}
        {% endif %}
        {# Sprache ändern #}
        <button id="toggle-lang" class="navbar-btn" style="padding-top:0.15em;padding-bottom:0.2em;"><i class="fa fa-globe fa-lg" aria-hidden="true" style="font-size:24px"> </i></button>
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        <form action="{% url "set_language" %}" method="post" class="navbar-form navbar-right">
            {% csrf_token %}
            <div id="lang-div" style="padding-top:0.4em;padding-bottom:0.1em; display: none;">
                <select name="language" onchange="this.form.submit()">
                {% for language in languages %}
                    <option value="{{ language.code }}"
                        {% if language.code == LANGUAGE_CODE %}selected="selected"{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
                </select>
            </div>
        </form>
    </div>
</div>

{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="margin-top: 5px;margin-bottom:0px;margin-left:5px;margin-right:5px">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
        </button>
        <label style="display:flex;font-weight:800;margin-bottom:0px;justify-content:center;" > {{ message }} </label>
  </div>
{% endfor %}

<!-- "content" contains everything that is not the header and can be modified by other html pages by using the block
"content" -->
<div name="content" class="container-fluid" style="padding-top: 2em;min-height:75vh;margin-bottom:50px;">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

<script>
    var button = document.getElementById('toggle-lang'); // Assumes element with id='button'

    button.onclick = function() {
        var div = document.getElementById('lang-div');
        if (div.style.display !== 'none') {
            div.style.display = 'none';
        }
        else {
            div.style.display = 'block';
        }
    };

</script>

ppsv/frontend/templates/frontend/homepage.html
{% extends 'frontend/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Home" %}{% endblock %}

{% block homepage_navbar_container %}
        <form class="navbar-form" action="{% url 'frontend:homepage' %}" style="float:left;padding-bottom: 0px;">
            <button type="submit" class="navbar-btn" style="color:#0a3d62;padding-top:0.42em;padding-bottom:0.42em;"><i class="fa fa-home fa-lg" aria-hidden="true" style="font-size:26px"></i></button>
        </form>
{% endblock homepage_navbar_container %}


{% block content %}
{% if user.is_authenticated %}
  <div style="display: flex;justify-content: center;position:relative;margin-top:20px">
    <div style="display: flex;justify-content: center; flex-direction: column;border: 3px solid rgba(10,61,98,1);border-radius:3px;padding: 15px 30px;padding-top:-15px;margin-top:5px;width:50%;min-width:500px;">
        <div style="position:relative;z-index:2;background-color:white; border: 2px solid rgba(10,61,98,1); top: -45px; left: 10px;padding: 2px 10px;width:220px;margin-bottom: -35px">
            <h2 style="margin:0px"> {% translate "What to do next" %}</h2>
        </div>
        {% for msg, link in recommendations.items %}
            <div style="display:flex; flex-direction:row;font-size:18px;margin-bottom:5px">
                <div style="overflow:hidden;text-overflow: ellipsis;width:100%;white-space: nowrap;background-color:white; border: 4px solid rgba(10,61,98,1);border-style: none none none solid;padding: 2px 5px;background-color:rgba(12,143,204,0.2);padding:3px">
                    <span style="margin:0px;"> {{ msg }} </span>
                </div>
                <a href="{% url link %}" class="undecorated-btn" style="padding:8px 10px;background-color:grey;border-radius: 3px; float:right;color:white;margin-left:5px">
                    <i class="fa fa-share" aria-hidden="true"></i>
                </a>
            </div>
        {% endfor %}
    </div>
  </div>
{% else %}
<div style="display: flex;justify-content: center;">
    <div style="display: flex;flex-direction:column;width:40%;min-width:360px;">
        <div style="display: flex;justify-content: center;border: 3px solid rgba(10,61,98,1);border-radius:3px;padding: 15px 30px;">
            <div style="min-width:300px;width: 20%;display: flex;flex-direction: column;text-align: center;">
                <div class="row-cols-sm-1" id="col_1">
                    <form method="post">
                        {% csrf_token %}
                        {{ login_form.as_p }}
                        <button class="sub-btn form-control" style="width: 100%" type="submit">Login</button>
                    </form>
                </div>
                    <div style="display:flex;flex-direction: row;vertical-align: baseline;margin-bottom: 10px">
                    <div style="background-color: #0a3d62;height: 2px;width: 48%;margin-top: 10px;margin-right: 2%"></div>
                        {% translate "or" %}
                    <div style="background-color: #0a3d62;height: 2px;width: 48%;margin-top: 10px;margin-left: 2%"></div>
                    </div>
                <div class="row-cols-sm-1" style="text-align: center">
                    <h6>{% translate "You do not have an account yet?" %}</h6>
                    <button class="sub-btn form-control" style="width: 100%" onclick="location.href='{% url 'frontend:register' %}'" type="button">{% translate "Register" %}</button>
                </div>
            </div>
        </div>
        <div style="display: flex;justify-content: center;border: 3px solid rgba(10,61,98,1);border-radius:3px;padding: 15px 30px;margin-top:5px;text-align:center;">
            <label style="font-size:40px"> {% translate "Welcome" %} <br>
                <label style="font-size:18px"> {% translate "This website serves as a platform for registering for seminars, internships and other courses. You can select topics and prioritize them across multiple courses." %} </label>
            </label>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}